version: "3.7"
services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - .env-example
    environment:
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "db"
      POSTGRES_HOST: "db"
    container_name: db_container_tests
    restart: always
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "db", "-U", "postgres"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 80s

  app:
    build:
      context: .
      dockerfile: Dockerfile-tests
    env_file:
      - .env-example
    container_name: api_container_tests
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && pytest -v -s test/test_menu.py && pytest -v -s test/test_submenu.py && pytest -v -s test/test_dish.py && pytest -v -s test/test_dishes_submenus_count.py"
    depends_on:
      - db


