FROM python:3.10-slim

RUN mkdir /ylab_example_tests

WORKDIR ylab_example_tests

COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["alembic upgrade head && pytest test/"]

COPY . .

