version: "3.7"
services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    container_name: db_container_tests
    restart: always
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U %{DB_USER}"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 80s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: api_container_tests
    restart: on-failure
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy